title: Suzanne Jin
description: Personal website and portfolio
url: "https://suzannejin.github.io"
baseurl: ""
username: suzannejin
intro_text: "Hi, I am Suzanne ðŸ‘‹"
links:
  github: https://github.com/suzannejin
  linkedin: https://linkedin.com/in/suzannejin
  twitter: https://x.com/suzannejin
  scholar: https://scholar.google.com/citations?user=7hSkrvoAAAAJ&hl=en
  email: suzanne.jin.yao@gmail.com
  cv: "#"

collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
theme: jekyll-theme-primer # Optional, but good for defaults if needed, though we are using custom layout
plugins:
  - jekyll-feed
  - jekyll-seo-tag
