title: Suzanne Jin
description: Personal website and portfolio
url: "https://suzannejin.github.io"
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
theme: jekyll-theme-primer # Optional, but good for defaults if needed, though we are using custom layout
plugins:
  - jekyll-feed
  - jekyll-seo-tag
