baseURL = 'https://suzannejin.github.io/'
languageCode = 'en-us'
title = 'Suzanne Jin'

[params]
  username = "suzannejin"
  intro_text = "Hi, I am Suzanne ðŸ‘‹"

[params.links]
  github = "https://github.com/suzannejin"
  linkedin = "https://linkedin.com/in/suzannejin"
  x = "https://x.com/suzannejin"
  scholar = "https://scholar.google.com/citations?user=7hSkrvoAAAAJ&hl=en"
  email = "suzanne[dot]jin[dot]yao[at]gmail[dot]com"
  cv = "#"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
